CREATE TABLE cars.user_car
(
    USER_ID BIGINT NOT NULL,
    CAR_ID BIGINT NOT NULL,
    PRIMARY KEY (USER_ID, CAR_ID),
    FOREIGN KEY (USER_ID) REFERENCES cars.app_user (ID),
    FOREIGN KEY (CAR_ID) REFERENCES cars.car (ID)
);